- name: Clone piston repo
  git:
    repo: https://github.com/engineer-man/piston.git
    dest: /opt/piston
    update: no

- name: Build piston docker image
  community.docker.docker_compose_v2:
    project_src: /opt/piston
    build: always

- name: Start piston containers
  community.docker.docker_compose_v2:
    project_src: /opt/piston
    state: present
