version: '3'

services:
  piston-api:
    image: ghcr.io/engineer-man/piston
    ports:
      - "2000:2000"
    environment:
      - SANDBOX_DISABLED=1
    restart: no

  # Example: Add 2 containers running your web app
  webapp1:
    image: nyanzey/koderush-front
    environment:
      - PISTON_URL=http://piston-api:2000
    depends_on:
      - piston-api
    ports:
      - "3000:3000"

  webapp2:
    image: nyanzey/koderush-front
    environment:
      - PISTON_URL=http://piston-api:2000
    depends_on:
      - piston-api
    ports:
      - "3001:3000"
